[gcp_service_account]
type = "service_account"
project_id = "SEU_PROJETO"
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "service-account@SEU_PROJETO.iam.gserviceaccount.com"
client_id = "..."
token_uri = "https://oauth2.googleapis.com/token"

[app]
spreadsheet_id = "COLE_AQUI_O_ID_DA_PLANILHA"
